### ISSUE TITLE
[BUG] Progress bar not showing up when enchanting jewlery

### ISSUE THREAD

**Issue by zyferis** [guillaume009/runelite-plugin-action-progress#13]
Progress bar not showing up when enchanting jewlery 
Tested on ruby ring, diamond bracelet, dragonstone bracelet

Enchant jewelry toggle is confirmed to be toggled on
progress bar confirmed to be working on other items such as crafting dhide and cleaning herbs

1) Cast respective enchant spell on diamond bracelet/dragonstone bracelet /ruby ring
2) Progress bar does not show up

**Comment by guillaume009** [comment]
Hi! I just tried it and it works on my end

![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/8568544/0ba400de-53c6-4bab-b92c-771afbd86b9c)

Do you have your client.log file? Maybe there will be something in there

**Comment by zyferis** [comment]
pics of plugin working and then testing on ruby ring

![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/69234187/2a77edd7-306f-41ed-a78a-d16c44ff05f1)
![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/69234187/66c58680-86d0-4b61-8a37-2a26bc8feb5b)

there is a warn in the client.log but unsure if is caused by action-progress plugin

>2023-08-20 16:08:05 SGT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
    at java.base/java.util.stream.ReferencePipeline$4$1.accept(Unknown Source)
    at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
    at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
    at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.base/java.util.stream.IntPipeline.allMatch(Unknown Source)
    at com.github.calebwhiting.runelite.plugins.actionprogress.Product.isMadeWith(Product.java:39)
    at com.github.calebwhiting.runelite.plugins.actionprogress.detect.UseItemOnItemDetector.onMenuOptionClicked(UseItemOnItemDetector.java:67)
    at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
    at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
    at net.runelite.client.callback.Hooks.post(Hooks.java:193)
    at qq.lm(qq.java:48345)
    at client.mm(client.java:12092)
    at client.ov(client.java:12081)
    at client.mb(client.java:3356)
    at client.bs(client.java:1162)
    at bm.ay(bm.java:401)
    at bm.run(bm.java:380)
    at java.base/java.lang.Thread.run(Unknown Source)

**Comment by guillaume009** [comment]
I do get that same exception when it works. What are you using to cast the spell? Directly fire and cosmic runes or some equipment to replace the fire runes?

**Comment by zyferis** [comment]
I've isolated the issue to be coming from using cosmic runes inside a rune pouch. 
Tried using empty hands and tome of fire + cosmic runes in inventory and the progress bar started showing up. 

There is no other warning in the logs.

**Comment by guillaume009** [comment]
Ah, you are right that the rune pouch wasn't taken into account. Good catch. I'll make a fix and post an update here once it's available

**Comment by guillaume009** [comment]
Has been merged in RuneLite. Please re-open if you are still experiencing issues
