### ISSUE TITLE
NPE on login

### ISSUE THREAD

**Issue by YvesW** [guillaume009/runelite-plugin-action-progress#21]
```
2023-10-16 07:11:14 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at com.github.calebwhiting.runelite.plugins.actionprogress.detect.SmithingDetector.onVarbitChanged(SmithingDetector.java:93)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:194)
	at client.lb(client.java:61582)
	at client.kq(client.java:34222)
	at client.hw(client.java:3098)
	at client.bo(client.java:1124)
	at bb.gv(bb.java:358)
	at bb.run(bb.java:335)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Login, and you get the above error.
Might have to get this 1 tick later (e.g. set a flag on login, then check onGameTick or maybe even a GameTick later), but I haven't looked at your code so that's just a guess.

**Comment by guillaume009** [comment]
Will look into it. Thanks for the information

**Comment by guillaume009** [comment]
Fix was merged few weeks back. Closing the issue
