### ISSUE TITLE
dragon bolts

### ISSUE THREAD

**Issue by Erutpur** [guillaume009/runelite-plugin-action-progress#5]
Hello sir,
when making tipped dragon bolts, e.g. rubies, the action progress is not shown.
Thanks overall for your app making osrs life more comfy :)

**Comment by zawe** [comment]
Here's an example of my client.logs while adding diamond tips to dragon bolts
```
java.lang.NullPointerException: null
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.IntPipeline.allMatch(Unknown Source)
	at com.github.calebwhiting.runelite.plugins.actionprogress.Product.isMadeWith(Product.java:39)
	at com.github.calebwhiting.runelite.plugins.actionprogress.detect.UseItemOnItemDetector.onMenuOptionClicked(UseItemOnItemDetector.java:67)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:193)
	at ce.kc(ce.java:17751)
	at client.tb(client.java:12101)
	at client.ii(client.java:3573)
	at client.bw(client.java:1134)
	at bq.bd(bq.java:363)
	at bq.run(bq.java:342)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-08-04 01:08:23 [Client] WARN  c.g.c.r.p.a.detect.ChatboxDetector - [*] Unhandled chatbox action
2023-08-04 01:08:23 [Client] WARN  c.g.c.r.p.a.detect.ChatboxDetector -  |-> Question: How many sets of 10 would you like to tip?
2023-08-04 01:08:23 [Client] WARN  c.g.c.r.p.a.detect.ChatboxDetector -  |-> Item ID: 21969
```

**Comment by guillaume009** [comment]
Thanks for the log! It pointed me to what I am confident is the issue. I wasn't able to try it, but I changed something and made the following PR on runelite. Whenever it gets merge you can try again and let me know if it fixed it.

https://github.com/runelite/plugin-hub/pull/4719

**Comment by zawe** [comment]
And thank you for the extremely quick fix.

I'll let you know when it's merged if it's working properly. I looked at the change and it looks like it might work. :)

**Comment by guillaume009** [comment]
Not sure @Erutpur would said it was a quick fix, but thanks :D

**Comment by guillaume009** [comment]
Have you been able to try it?

**Comment by zawe** [comment]
@guillaume009 It looks like adding diamond bolt tips to a dragon bolt is still way off. I finish the action much earlier.
It seems to incorrectly identify what action is being triggered. I was adding 20 diamond bolt tips to 20 dragon bolts and it showed the following on the info box:
![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/4064372/e714f5ab-ef17-4b43-835a-adc2ab29d270)

It shouldn't be 5 actions, but actually 2 each(10 bolts each).

I have a clients log error, but I'm not sure if this one is related:

```
java.lang.NullPointerException: null
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.IntPipeline.allMatch(Unknown Source)
	at com.github.calebwhiting.runelite.plugins.actionprogress.Product.isMadeWith(Product.java:39)
	at com.github.calebwhiting.runelite.plugins.actionprogress.detect.UseItemOnItemDetector.onMenuOptionClicked(UseItemOnItemDetector.java:67)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:193)
	at ce.kc(ce.java:17751)
	at client.tb(client.java:12101)
	at client.ii(client.java:3573)
	at client.bw(client.java:1134)
	at bq.bd(bq.java:363)
	at bq.run(bq.java:342)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by guillaume009** [comment]
Alright, I was able to try it and there were couple of issues, but it should be sorted out now. I created the following PR on RuneLite. Once it's merged it should be fixed for good :) 

[#4787](https://github.com/runelite/plugin-hub/pull/4787)

**Comment by guillaume009** [comment]
Fix was merged, please re-open if the issue persist
