### ISSUE TITLE
[BUG] GOTR checkInMainRegion NPE

### ISSUE THREAD

**Issue by YvesW** [guillaume009/runelite-plugin-action-progress#72]
You are probably trying to use an array too early before it's populated. I've not looked at your code though.

**To Reproduce**
1. Start the client with the plugin enabled.
2. Login.

```2024-07-25 12:12:28 CEST [Client] DEBUG injected-client - Game state changed: LOGGING_IN
2024-07-25 12:12:28 CEST [Client] DEBUG c.d.o.f.util.ColosseumStateTracker - Colosseum state change ColosseumState(inLobby=false, inColosseum=false, waveNumber=1, waveStarted=false) => ColosseumState(inLobby=false, inColosseum=false, waveNumber=1, waveStarted=false)
2024-07-25 12:12:29 CEST [Client] DEBUG injected-client - Chat message type CONSOLE: <colHIGHLIGHT>Daily item charges have been reset.
2024-07-25 12:12:29 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at java.base/java.util.Arrays.stream(Arrays.java:5645)
	at com.github.calebwhiting.runelite.plugins.actionprogress.detect.GuardianOfTheRift.checkInMainRegion(GuardianOfTheRift.java:62)
	at com.github.calebwhiting.runelite.plugins.actionprogress.detect.GuardianOfTheRift.onChatMessage(GuardianOfTheRift.java:68)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:202)
	at client.addChatMessage(client.java:42693)
	at client.addChatMessage(client.java:11642)
	at net.runelite.client.chat.ChatMessageManager.add(ChatMessageManager.java:824)
	at net.runelite.client.chat.ChatMessageManager.process(ChatMessageManager.java:810)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:245)
	at client.ff(client.java:58760)
	at client.bw(client.java)
	at bs.nd(bs.java:388)
	at bs.yl(bs.java)
	at bs.run(bs.java:34115)
	at java.base/java.lang.Thread.run(Thread.java:829)
2024-07-25 12:12:31 CEST [pool-9-thread-1] DEBUG n.r.c.p.w.WorldHopperPlugin - Done pinging worlds in PT34.2836635S```

**Comment by JonneSaloranta** [comment]
Could not reproduce. Is this still an issue? Please provide more information.

**Comment by guillaume009** [comment]
Your proposed fix will be live once the following PR is merged.

https://github.com/runelite/plugin-hub/pull/7196
